### ISSUE TITLE
Bugs on Firefox Beta 103.0b2 (32-bit)

### ISSUE THREAD

**Issue by 123-bott** [xiaoxiaoflood/firefox-scripts#153]
Firefox and Build Version: Firefox Beta 103.0b2 (32-bit)
Scripts Install Date: June 29, 2022
Scripts/Extensions: PrivateTab and Master Password+
Problem/Bug:

PrivateTab causes Windows and Tabs issues. Windows don't load, and tabs glitch when in use/enabled.

![PrivateTab1](https://user-images.githubusercontent.com/57055585/176485855-4fbd674c-3e1d-44d4-b785-5c77d30d4a55.PNG)
![PrivateTab2](https://user-images.githubusercontent.com/57055585/176485867-85933032-d92e-43b6-8d81-3df9dd536291.PNG)

Master Password+ displays the windows from Firefox "Password Required." This bug doesn't happen on older versions of Firefox (I think before the 100 Version Build Release).

![MasterPassword1](https://user-images.githubusercontent.com/57055585/176486170-6c09c6b7-a8d6-4127-9bd2-1c97a5b8ae2d.PNG)

Before opening this issue, I checked and reinstalled all scripts and js, so it isn't because of old scripts and files.

**Comment by xiaoxiaoflood** [comment]
PrivateTab is fixed.

Regarding, MP+ I don't thing anything has changed. It never intended to prevent "window" password prompting, that can be triggered by Fx when you have a saved login in the page of active tab. It's not a bug or something new.

**Comment by benzBrake** [comment]
> 
There's still a problem with privateTab
![privatTab](https://user-images.githubusercontent.com/11323774/177032803-5ef6a392-0b7a-48f3-b29a-f1a3139985d3.jpg)

**Comment by xiaoxiaoflood** [comment]
I can't see what's wrong.

**Comment by benzBrake** [comment]
> I can't see what's wrong.

When pin more than 2 tabs, after closing all not pinned tabs and add a newtab, the last pin tab will show after the new tab

**Comment by xiaoxiaoflood** [comment]
Thanks. I believe now it's really fixed.
