### ISSUE TITLE
DownThemAll! Manager colum order reseting

### ISSUE THREAD

**Issue by almtst** [xiaoxiaoflood/firefox-scripts#211]
Every time you open the download manager the column order is reset, also if a column is smaller than its title the text will overlap the title of the next column, making them unreadable.

**Comment by xiaoxiaoflood** [comment]
> if a column is smaller than its title the text will overlap the title of the next column, making them unreadable.

This was an issue by Firefox itself and was already fixed in last versions.

> Every time you open the download manager the column order is reset

I can't reproduce, here for me it's remembered.

**Comment by almtst** [comment]
Hello, text overlap seems to be fixed but column order resetting is still a problem on my end, I even tried a new profile but got the same result.
